runtime: go114
instance_class: F1
automatic_scaling:
  max_instances: 1
  min_instances: 0
  max_idle_instances: 1
  min_idle_instances: 0
  target_cpu_utilization: 0.95
  target_throughput_utilization: 0.95
  max_concurrent_requests: 80
  max_pending_latency: 15s
  min_pending_latency: 15s

default_expiration: "7d"

env_variables:
  HOST: "https://user.slothninja.com"
  DATASTORE_PROJECT_ID: "user-slothninja-games"
  CLIENT_ID: "435340145701-t5o50sjq7hsbilopgreobhvrv30e1tj4.apps.googleusercontent.com"
  CLIENT_SECRET: "H79UlEDjN5Q6nBMGaXuvaGkH"
  NODE_ENV: "production"
  # MJ_API_KEY_PUB: "0b66e3cf5d4b5a5c536ef1a289b58d79"
  # MJ_API_KEY_PRIV: "e4ba83076c32f4732e84a1b05cb4e3e5"
          

inbound_services:
- warmup

handlers:
- url: /favicon\.ico
  static_files: dist/favicon.ico
  upload: dist/favicon\.ico

- url: /
  static_files: dist/index.html
  upload: dist/index\.html

- url: /index\.html
  static_files: dist/index.html
  upload: dist/index\.html

- url: /css
  static_dir: dist/css

- url: /img
  static_dir: dist/img

- url: /js
  static_dir: dist/js

- url: /robots\.txt
  static_files: public/robots.txt
  upload: public/robots\.txt

- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto
